---
title: "AWS Cloud Improvements Make Marketing Magic"
subtitle: Securing and unleashing the power of the cloud!
client:
    name: Make Marketing Magic B.V.
    short_name: MMM
    contact_person: Gijs Oliemans
format: technative-theme-revealjs
incremental: false
embed-resources: true
date-format: "MMMM YYYY"
---

## Nice to meet you! {dark-background="false" background-image="img/2.png"}


**Born in the Cloud:** TechNative helps clients getting more out of their digital journeys.
From software development & testing to cloud management.
<br/>
<br/>

**Based in Amersfoort, The Netherlands:** with currently a team of ±35 DevOps
professionals and software Architects we help clients throughout Europe with complex
platforms or scalability issues.
<br/>
<br/>

**We love Open Source:** 90% of the projects we do are based on Open Source software,
predominantly on Linux and in mostly in public or private Cloud.
<br/>
<br/>

**Official business partner:** All our engineers are AWS certified and we are an official
recognized AWS Business Partner. Next to that TechNative is the largest FinOps
Certified Business partner in the BeNeLux.


## A small company with large clients { background-image="img/3.png"  }
<br/>

##### We successfully help a number of clients throughout Europe: {.white-text}

::: {.highlight-text}
**AutoMobile.it** – the largest online vehicle marketplace in Italy.

**Dreamlines.com** – Europe’s largest e-commerce channel for online booking of cruise holidays.

**LePaya.com** – one of the top 50 fastest growing startups in The Netherlands.

**Ahold DelHaize** – one of the larger supermarket retailers in The Netherlands.

**Volksbank** – a relatively small Dutch bank with over 3M clients.

**Recharge.com** – the leading online branded payments marketplace in 30+ countries.
:::

## How do we differentiate from others?  {.center background-image="img/4.png" .white-text}

::: {.highlight-text}
TechNative is grown on good old Dutch pragmatism. We are only successful if you are successful. Because of
this we look at technology as a vehicle, not a destination.
:::

# About this proposal { data-background-color="#112f41" }

After a Well Architected review TechNative has created a report with
recommendations. Following this report together with the knowledge of the
recent security incident, we have made a proposal with improvements.

## Briefing { data-background-color="#112f41" .center}

- MMM has several EC2 machine's running with a PHP application server.
- Compute resources orchestrated by Elastic Beanstalk.
- Lack of security policy and pre-defined cloud architecture is missing
- At current scale security and controllability problems arise.
- MMM needs help to gain back grip and control over AWS Cloud.

## Brief solution outline { data-background-color="#112f41"  .center}

Our proposal can be roughly divided in two major components:

- Securing and improving the existing platform.

- Implementing a new multi-account IaC-based platform to which new and
  existing services fluidly can be migrated.

# Quick Wins { data-background-color="#112f41" }

# Enhanced Security { data-background-color="#112f41" }

- Hardening current infra with wide pallet of security tools
- Buy time to migrate to a secure by design architecture.

# Observability { data-background-color="#112f41" }

By implementing TechNative's robust extendable observability module, MMM gets:

- Rapid identification of performance issues
- Proactive capacity planning and resource optimization
- Improved troubleshooting and debugging capabilities
- Enhanced security monitoring and incident response

# Infrastructure as Code (IaC) { data-background-color="#112f41" }

Introducing IaC has many advantages:

:::: {.columns}


::: {.column width="60%"}
- Greater efficiency and cost savings
- Faster provisioning of resources
- Version control
- Roll-back scenario's
:::

::: {.column width="40%"}
- Secure by design
- Increased consistency
- Increased reliability
- Improved scalability
- Reproducibility
:::

::::

# WAR Risks mitigated { data-background-color="#112f41" .center}

Proposal mitigates identified risks by more then 50%.

This makes MMM earn $ 5.000 hosting credits.

# Tasks { data-background-color="#112f41" }


## Onboarding {{< meta client.short_name >}} as TechNative AWS client { data-background-color="#112f41" .center}


- Becoming a reseller customer involves registering a client vendor registration with AWS.

- As reseller customer, {{< meta client.short_name >}} saves 3% in hosting costs.

- These hours can be spent as advisory hours performed by our Cloud Engineers.

## Securing Existing Workload Account {.center data-background-color="#112f41" } 

:::: {.columns}

::: {.column width="60%"}
- Forensic Investigation Recent Security Incident
- Set up Security Hub
- Extended Prowler Security Scan
- Implement SSM Patch Manager
- Implement CloudWatch Agents
:::

::: {.column width="40%"}
- Implement Standard Hardening tools
- Minimize Global Attack Surface
- IAM review and refactoring
- Back-up's review and refactoring
:::

::::

## Implementing new well architected platform { data-background-color="#112f41" }

- Setting up Landing Zone and Generic AWS accounts
- Setting up Boilerplate Workload AWS accounts
- Setting up and configuring Monitoring and alarms

# Planning { data-background-color="#112f41" }

After approval, this project will take approximately 8 weeks to complete.

# Project tasks and pricing { data-background-color="#112f41" }


| Description                                        |      Hours |
|:---------------------------------------------------|-----------:|
| Onboarding MMM as TechNative AWS client            |          1 |
| Securing Existing Workload Account                 |        104 |
| Implementing new well architected platform         |         56 |
| Documentation                                      |          4 |
| Training                                           |          4 |
| Project management                                 |         25 |
| TOTAL                                              |        194 |
| Budget with a blended fee of €105,00 p/hour        |   € 20.370 |

